# 05 - Employee Attrition Risk Scoring System

## Objective

Convert machine learning predictions into employee risk scores and risk categories that HR teams can use for proactive retention planning.

## Business Goal

Instead of predicting only Attrition = Yes / No,
generate:

- Attrition Probability
- Risk Score
- Risk Level (Low / Medium / High)

This output will become the input dataset for Power BI dashboards and business reporting.

## 1. Load Dataset

In [52]:
import pandas as pd

df = pd.read_csv("../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

## 2. Recreate Modeling Dataset

In [53]:
df["Attrition"] = df["Attrition"].map({"Yes": 1, "No": 0})

X = df.drop(columns=["Attrition"])
y = df["Attrition"]

X = pd.get_dummies(X, drop_first=True)

## 3. Train-Test Split

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

## 4. Scale Features for Logistic Regression

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## 5. Train Final Logistic Regression Model

In [56]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

lr.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=2000)

## 6. Generate Attrition Probabilities

In [57]:
y_prob = lr.predict_proba(X_test_scaled)[:, 1]

y_prob[:10]

array([0.29293576, 0.02032816, 0.30993067, 0.04876736, 0.65156982,
       0.67094635, 0.07806038, 0.21161841, 0.01983734, 0.24541766])

## 7. Create Employee Risk Levels

In [58]:
risk_df = X_test.copy()

risk_df["Actual_Attrition"] = y_test.values

risk_df["Attrition_Probability"] = y_prob

risk_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,Actual_Attrition,Attrition_Probability
1061,24,830,13,2,1,1495,4,78,3,1,...,False,False,False,False,True,True,False,False,0,0.292936
891,44,1117,2,1,1,1246,1,72,4,1,...,False,False,True,False,False,True,False,False,0,0.020328
456,31,688,7,3,1,613,3,44,2,3,...,False,False,False,False,False,False,False,False,0,0.309931
922,44,1199,4,2,1,1288,3,92,4,5,...,False,False,False,False,False,False,False,False,0,0.048767
69,36,318,9,3,1,90,4,79,2,1,...,False,False,True,False,False,True,False,True,1,0.651570

### Define Risk Categories

Low Risk    : 0.00 - 0.30

Medium Risk : 0.30 - 0.60

High Risk   : 0.60 - 1.00

In [59]:
def assign_risk(prob):

    if prob < 0.30:
        return "Low"

    elif prob < 0.60:
        return "Medium"

    else:
        return "High"


risk_df["Risk_Level"] = risk_df["Attrition_Probability"].apply(assign_risk)

risk_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,Actual_Attrition,Attrition_Probability,Risk_Level
1061,24,830,13,2,1,1495,4,78,3,1,...,False,False,False,True,True,False,False,0,0.292936,Low
891,44,1117,2,1,1,1246,1,72,4,1,...,False,True,False,False,True,False,False,0,0.020328,Low
456,31,688,7,3,1,613,3,44,2,3,...,False,False,False,False,False,False,False,0,0.309931,Medium
922,44,1199,4,2,1,1288,3,92,4,5,...,False,False,False,False,False,False,False,0,0.048767,Low
69,36,318,9,3,1,90,4,79,2,1,...,False,True,False,False,True,False,True,1,0.651570,High

## 8. Risk Distribution Analysis

In [60]:
risk_df["Risk_Level"].value_counts()

Risk_Level
Low       161
Medium     71
High       62
Name: count, dtype: int64

In [61]:
risk_df["Risk_Level"].value_counts(normalize=True) * 100

Risk_Level
Low       54.761905
Medium    24.149660
High      21.088435
Name: proportion, dtype: float64

## 9. Department Risk Analysis

Analyze risk distribution across departments to identify business units requiring retention intervention.

In [62]:
department_info = df.loc[X_test.index, ["Department"]]

risk_df = risk_df.merge(
    department_info,
    left_index=True,
    right_index=True
)

risk_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,Actual_Attrition,Attrition_Probability,Risk_Level,Department
1061,24,830,13,2,1,1495,4,78,3,1,...,False,False,True,True,False,False,0,0.292936,Low,Sales
891,44,1117,2,1,1,1246,1,72,4,1,...,True,False,False,True,False,False,0,0.020328,Low,Research & Development
456,31,688,7,3,1,613,3,44,2,3,...,False,False,False,False,False,False,0,0.309931,Medium,Sales
922,44,1199,4,2,1,1288,3,92,4,5,...,False,False,False,False,False,False,0,0.048767,Low,Research & Development
69,36,318,9,3,1,90,4,79,2,1,...,True,False,False,True,False,True,1,0.651570,High,Research & Development

In [63]:
pd.crosstab(
    risk_df["Department"],
    risk_df["Risk_Level"],
    normalize="index"
) * 100

Risk_Level                   High        Low     Medium
Department
Human Resources         20.000000  53.333333  26.666667
Research & Development  16.751269  59.390863  23.857868
Sales                   31.707317  43.902439  24.390244

### Department Risk Insights

Observe which departments contain the highest percentage of High Risk employees.

## 10. Job Role Risk Analysis

Identify job roles with elevated attrition risk.

In [64]:
jobrole_info = df.loc[X_test.index, ["JobRole"]]

risk_df = risk_df.merge(
    jobrole_info,
    left_index=True,
    right_index=True
)

risk_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes,Actual_Attrition,Attrition_Probability,Risk_Level,Department,JobRole
1061,24,830,13,2,1,1495,4,78,3,1,...,False,True,True,False,False,0,0.292936,Low,Sales,Sales Representative
891,44,1117,2,1,1,1246,1,72,4,1,...,False,False,True,False,False,0,0.020328,Low,Research & Development,Research Scientist
456,31,688,7,3,1,613,3,44,2,3,...,False,False,False,False,False,0,0.309931,Medium,Sales,Manager
922,44,1199,4,2,1,1288,3,92,4,5,...,False,False,False,False,False,0,0.048767,Low,Research & Development,Manager
69,36,318,9,3,1,90,4,79,2,1,...,False,False,True,False,True,1,0.651570,High,Research & Development,Research Scientist

In [65]:
pd.crosstab(
    risk_df["JobRole"],
    risk_df["Risk_Level"],
    normalize="index"
) * 100

Risk_Level                      High         Low     Medium
JobRole
Healthcare Representative   4.347826   65.217391  30.434783
Human Resources            27.272727   45.454545  27.272727
Laboratory Technician      25.000000   38.636364  36.363636
Manager                     5.263158   84.210526  10.526316
Manufacturing Director     12.500000   65.625000  21.875000
Research Director           0.000000  100.000000   0.000000
Research Scientist         22.222222   54.166667  23.611111
Sales Executive            22.641509   52.830189  24.528302
Sales Representative       60.869565   13.043478  26.086957

### Job Role Risk Insights

Identify job roles requiring targeted retention programs.

In [66]:
pd.crosstab(
    risk_df["Department"],
    risk_df["Risk_Level"],
    normalize="index"
) * 100

Risk_Level                   High        Low     Medium
Department
Human Resources         20.000000  53.333333  26.666667
Research & Development  16.751269  59.390863  23.857868
Sales                   31.707317  43.902439  24.390244

In [67]:
pd.crosstab(
    risk_df["JobRole"],
    risk_df["Risk_Level"],
    normalize="index"
) * 100

Risk_Level                      High         Low     Medium
JobRole
Healthcare Representative   4.347826   65.217391  30.434783
Human Resources            27.272727   45.454545  27.272727
Laboratory Technician      25.000000   38.636364  36.363636
Manager                     5.263158   84.210526  10.526316
Manufacturing Director     12.500000   65.625000  21.875000
Research Director           0.000000  100.000000   0.000000
Research Scientist         22.222222   54.166667  23.611111
Sales Executive            22.641509   52.830189  24.528302
Sales Representative       60.869565   13.043478  26.086957

## Key Business Findings

### Department-Level Findings

- Sales department has the highest concentration of High Risk employees.
- Research & Development shows the lowest attrition risk profile.

### Job Role Findings

- Sales Representatives exhibit the highest attrition risk.
- Laboratory Technicians and Human Resources roles also show elevated risk levels.
- Managers and Research Directors demonstrate strong retention profiles.

### HR Recommendation

Prioritize retention initiatives for:

1. Sales Representatives
2. Sales Executives
3. Laboratory Technicians
4. Human Resources employees

Focus areas:
- Compensation review
- Career progression
- Work-life balance
- Manager engagement

## 11. Export Final Risk Scoring Dataset

In [69]:
risk_df.columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Research & Development', 'Department_Sales',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Male',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'MaritalStatus_Married', 'MaritalStatus_Single', 'OverTime_Yes',
       'Actual_Attrition', 'Attrition_Probability', 'Risk_Level', 'Department',
       'JobRole'],
      dtype='str')

## 12. Create Business-Friendly Risk Dataset

In [70]:
business_df = df.loc[X_test.index, [
    "EmployeeNumber",
    "Department",
    "JobRole",
    "Age",
    "MonthlyIncome",
    "YearsAtCompany"
]].copy()

business_df["Actual_Attrition"] = y_test.values

business_df["Attrition_Probability"] = y_prob

business_df["Risk_Level"] = business_df[
    "Attrition_Probability"
].apply(assign_risk)

business_df.head()

,EmployeeNumber,Department,JobRole,Age,MonthlyIncome,YearsAtCompany,Actual_Attrition,Attrition_Probability,Risk_Level
1061,1495,Sales,Sales Representative,24,2033,1,0,0.292936,Low
891,1246,Research & Development,Research Scientist,44,2011,10,0,0.020328,Low
456,613,Sales,Manager,31,11557,5,0,0.309931,Medium
922,1288,Research & Development,Manager,44,19190,25,0,0.048767,Low
69,90,Research & Development,Research Scientist,36,3388,1,1,0.651570,High

In [71]:
business_df.info()

<class 'pandas.DataFrame'>
Index: 294 entries, 1061 to 285
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   EmployeeNumber         294 non-null    int64
 1   Department             294 non-null    str
 2   JobRole                294 non-null    str
 3   Age                    294 non-null    int64
 4   MonthlyIncome          294 non-null    int64
 5   YearsAtCompany         294 non-null    int64
 6   Actual_Attrition       294 non-null    int64
 7   Attrition_Probability  294 non-null    float64
 8   Risk_Level             294 non-null    str
dtypes: float64(1), int64(5), str(3)
memory usage: 23.0 KB

In [72]:
business_df.head(10)

,EmployeeNumber,Department,JobRole,Age,MonthlyIncome,YearsAtCompany,Actual_Attrition,Attrition_Probability,Risk_Level
1061,1495,Sales,Sales Representative,24,2033,1,0,0.292936,Low
891,1246,Research & Development,Research Scientist,44,2011,10,0,0.020328,Low
456,613,Sales,Manager,31,11557,5,0,0.309931,Medium
922,1288,Research & Development,Manager,44,19190,25,0,0.048767,Low
69,90,Research & Development,Research Scientist,36,3388,1,1,0.651570,High
1164,1641,Research & Development,Manufacturing Director,40,7945,4,0,0.670946,High
406,543,Research & Development,Manufacturing Director,52,7969,5,0,0.078060,Low
1330,1866,Research & Development,Manager,43,19392,16,0,0.211618,Low
1232,1728,Research & Development,Manufacturing Director,35,6883,7,0,0.019837,Low
1311,1839,Research & Development,Research Scientist,18,1514,0,0,0.245418,Low

## 13. Export Risk Scoring Dataset

In [76]:
business_df.to_csv(
    "../data/cleaned/employee_attrition_risk_scores.csv",
    index=False
)

print("Risk scoring dataset exported successfully.")

Risk scoring dataset exported successfully.